---
- name: first project
  hosts: localhost
  become: yes
  vars:
    db_name: azeemdb
    db_user: azeem
    db_password: azeem
  tasks:
    - name: install dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - python3
        - python3-setuptools
        - python3-dev
        - build-essential
        - python3-pip
        - python3-mysqldb

    - name: install mysql database
      apt:
          name: "{{item}}"
          state: present
      with_items:
               - mysql-server
               - mysql-client

    - name: starting mysql
      service:
       name: mysql
       state: restarted
       force: yes

    - name: create database
      mysql_db:
        name:  mydatabase
        state: present
        login_user: root
        login_host: localhost
        login_password:

    - name: create user
      mysql_user:
        name: admin123
        password: admin123
        priv: '*.*:ALL'
        state: present

    - name: install python flask dependenices
      pip:
           name: "{{item}}"
           state: present
      with_items:
                   - flask
                   - flask-mysql
    - name: copy web-server code
      copy:
          src: app.py
          dest: /opt/app.py
    - name: start web-application
      shell: FLASK_ALL=/opt/app.py nohup flask run --host=localhost